### PR TITLE
feat: allow a customizable section list text style

### PR DESCRIPTION
**Pull request by bksantiago**
This will allow devs to pass `Text` specific styles (color, etc.)

### CODE REVIEW

**Review by anhtuank7c — APPROVED** [review]
Thank you

**Comment by bksantiago** [comment]
@anhtuank7c Do you mind publishing this changes to npm? Thanks

**Comment by kokweng91** [comment]
@anhtuank7c Can you publish this to npm?? Thanks!

**Comment by alainib** [comment]
how to use it please ? available on npm ?

**Comment by alainib** [comment]
available on npm ?
i use "react-native-atoz-listview": "0.0.7" 
and code like this

**Comment by alainib** [comment]
@kokweng91  it is added in last npm version , try this : 
      
       sectionListStyle={{ width: 25, justifyContent: "center", alignItems: "center" }}

**Pull request merged**
